# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    pre_install:
      # Install MkDocs Material theme
      - pip install mkdocs-material

# Tell RTD we are building MkDocs docs
mkdocs:
  configuration: mkdocs.yml
